// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH8CA4otXlMW_8TOwIqHR_qCsGSQP3R64',
    appId: '1:794556877104:web:2f972d43b06a6015b3e0f5',
    messagingSenderId: '794556877104',
    projectId: 'solo-rehearsal',
    authDomain: 'solo-rehearsal.firebaseapp.com',
    storageBucket: 'solo-rehearsal.appspot.com',
    measurementId: 'G-J6KT0Z8322',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNyrlx8oMgr1UkDW7ok00a5FfiKG6wVJE',
    appId: '1:794556877104:android:10aa7c5c9eec71f3b3e0f5',
    messagingSenderId: '794556877104',
    projectId: 'solo-rehearsal',
    storageBucket: 'solo-rehearsal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD4rDGHITQiFeVW9BDMVQkHwcA4aDwoZk',
    appId: '1:794556877104:ios:0bb10b14940b087fb3e0f5',
    messagingSenderId: '794556877104',
    projectId: 'solo-rehearsal',
    storageBucket: 'solo-rehearsal.appspot.com',
    iosClientId: '794556877104-7dt2jr6o8rpti9e5glourl3prck3tn6f.apps.googleusercontent.com',
    iosBundleId: 'com.priyaiyer.soloRehearsal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD4rDGHITQiFeVW9BDMVQkHwcA4aDwoZk',
    appId: '1:794556877104:ios:a99c24346c597c70b3e0f5',
    messagingSenderId: '794556877104',
    projectId: 'solo-rehearsal',
    storageBucket: 'solo-rehearsal.appspot.com',
    iosClientId: '794556877104-2gml8n95ad03ossqd1diqrtnisibkhe2.apps.googleusercontent.com',
    iosBundleId: 'com.example.soloRehearsal.RunnerTests',
  );
}
